### ISSUE TITLE
use light sensor instead of characteristic?

### ISSUE THREAD

**Issue by lg** [ebaauw/homebridge-soma#13]
hello! i'm using this plugin for getting SOMA Tilt 2s onto Home Assistant. i can see in HomeKit that the light level is being exported (as apple writes it in 'lux' units), but when importing the devices into Home Assistant all i get is the main control of the blinds and the battery level. would it be possible to create an actual sensor "device" so i can use the status for automation? (like the battery is now)

**Comment by ebaauw** [comment]
Technically, yes.  In fact, I used to expose a separate _Light Sensor_ service before v0.0.14.  Functionally, that didn’t work out (see also #3):
- Home doesn’t like accessories with both an actuator and a sensor.  It shows a combined tile, but the “accessories” cannot be shown as separate tiles, requiring an additional touch before you can control the blinds;
- The SOMA device doesn’t provide a lux value, and I don’t know how to convert the raw value reported by the solar panel to lux.  Neither do the otherwise very helpful folks at Wazombi labs;
- The sensor actually measures the outside light level, not the room light level, so the sensor should be in a separate “room” as the blind.

So the choice was either to expose the light sensor as a separate accessory, or as an additional characteristic on the _Window Covering_ service.  I chose the latter, so Home doesn’t show it (as it would be reporting an incorrect light level for the “room”), but you can use it for automations in Eve or Home+.  I would still recommend to use on-device triggers though, disabling or re-enabling these from HomeKit automations to handle “Watch TV” scene logic.

I don’t use nor support Home Assistant.  I would never suggest chaining Homebridge and Home Assistant, and would recommend a native integration to Home Assistant.  I won’t be making any changes solely for Home Assistant.

**Comment by lg** [comment]
gotcha! perhaps make it configurable? fwiw this is the beta SOMA Tilt controller out there for Home Assistant too. additionally i do want to use the outside light level -- im using it as a way of telling if to close the blinds, but also as a signal for my curtains which dont have a sensor. finally im ok with an inaccurate lux value, so long as it's consistent.

just want to say, thank you a ton for working on this, super helpful! 🙏

**Comment by ebaauw** [comment]
As a workaround, you could use the on-device trigger to close the blinds, and an HA automation to close the curtains when the blinds are closed.  I love the idea to “set and forget” on-device automations, that work independently from any server.  The only reason I need integration is the TV scene, otherwise my Venetian blinds handle sunrise, sunset, and straight sunlight onto the window by themselves.
