### ISSUE TITLE
Plugin is running fine and all the sudden, I need to restart the Bridge to make it working again

### ISSUE THREAD

**Issue by Hedrakk** [ebaauw/homebridge-soma#19]
Hi,

I've installed your plugin in my HOOBS box and I was really impressed in the fact that I have more information available using your HOOBS/Homebridge plugin than using the official SOMA-Connect dongle.

That being said, it often stop working. I would say that for 3 or 4 days, every morning when I try to open my blinds with my HomeKit  Scene, it doesn't respond at all. 

I noticed that in the pluging options, you can set a value to resart homebridge soma, but it doesn't seem to be helping

I've attached the logs from HOOBS, but just prior to submit this, I retried to control my blinds with HomeKit and it was working... So it seems to get fixed by itself, although it would be nice to understand why it is doing that and how to set up the plugging so it would be more stable.

Thanks 

[SOMA_Plugin_Log.txt](https://github.com/ebaauw/homebridge-soma/files/8429441/SOMA_Plugin_Log.txt)

**Comment by Hedrakk** [comment]
A few minutes after I've submit my first message, the issues came back, so here's my HOOBS log file while it was not responding.

[SOMA_Plugin_Log2.txt](https://github.com/ebaauw/homebridge-soma/files/8429507/SOMA_Plugin_Log2.txt)


Thanks

**Comment by ebaauw** [comment]
The issues are caused by failing BLE communication with the Soma shades.  I have no idea what’s causing this.  Could be related to the radio signal; could be the BLE hardware or stack, I’ve never tried this on a 64-bit OS nor on Hoobs; could be the Noble BLE library.  Could even be a combination of these, making it even harder to diagnose.

I found that sometimes Noble seems to lock up, and restarting NodeJS is the only resolution, that’s why I added the autorestart option.  I cannot seem to reset Noble through it’s API.  The Pi doesn’t have the greatest BLE antenna, make sure it’s within 4-5m of the shades, with a direct line of sight, and the antenna facing the blinds.
