### ISSUE TITLE
Memory is full when plugin is active

### ISSUE THREAD

**Issue by Vollerplasc** [ebaauw/homebridge-soma#22]
I run the Soma plugin as a child bridge, but when the plugin is running, the memory of the home bridge gets fuller from day to day, until after 5 days the free memory only has a value of 0.03 GB and the home bridge stops responding and it can only be switched off and restarted by disconnecting the operating voltage. If I haven't installed the plugin, the home bridge runs without problems.

**Comment by ebaauw** [comment]
Please provide detailed information:
- What system are you running on?
- What memory is "full"?  How do you measure that?
- Which process, main bridge vs hb-service vs child bridge is consuming how much physical memory vs virtual memory?

**Comment by Vollerplasc** [comment]
1. ob a Raspberry 3b+
2. Homebridge system, according to the display, the memory is full
3. Unfortunately, I can't say that, I only have the display of the memory of the Raspberry

**Comment by ebaauw** [comment]
Sorry, then I cannot help you determining whether your issue is caused by Homebridge SOMA.  It's a bit like blaming your hangover on the last beer, because you were still feeling fine after each of the first 20 beers.  NodeJS is quite memory hungry, and each child bridge is an additional NodeJS process (next to the main bridge and `hb-service`).

In general, Raspberry Pi OS will try and use all available physical memory, largely for the file system cache.  It uses a swap file for when memory requirements exceed the physical memory.  When the swap file fills up, the system becomes unresponsive.  The default swap file of 100MB is a joke; I've increased that to 2GB on all my Pi systems (even on my 8GB Pi 4B).

I use `htop` to monitor resource usage: the swap usage is displayed on the lower bar in the screen header.  By selecting the _Tree_ view (F5) and then sorting on RESV (click on the header), you get a good overview of the memory usage of each of the NodeJS/Homebridge processes.  In my case, `hb-service` is typically more memory hungry than Homebridge or any of the child bridges.  You want to monitor VIRT (virtual memory) and RES (physical memory).  Note the values after (re)starting Homebridge and see how badly they increase over time.  It's normal that they increase somewhat; I would only worry if VIRT grows beyond 250M or RES beyond 120M.

**Comment by Vollerplasc** [comment]
Hello, I was still at work this morning and didn't quite know how to get the data to you.
I have now entered htop and pressed F5, the following screenshot, s
<img width="931" alt="Bildschirmfoto 2022-07-22 um 16 41 24" src="https://user-images.githubusercontent.com/109787025/180463594-46455a98-2557-4a76-8e5f-94425206ec0b.png">
hows the data

**Comment by ebaauw** [comment]
Cool, you want to take a daily or half-daily screenshot like this, checking the _Swp_ on the top (when the `0K/100.0M` nears `100.0M/100.0M` you're in danger), and the VIRT and RES values for Homebridge SOMA (currently 184M and 80K).  Note that currently, `hb-servcie` and the main Homebridge instance (with the UI) each use more memory than Homebridge SOMA.

**Comment by Vollerplasc** [comment]
Hello good morning, I have already made 3 screenshots yesterday and today one, you can see well how the memory fills.
I will make the next one around 12 noon and can then unfortunately only make the next one around 11 pm, because I'm on lunch shift.
I had on the weekend times the ChildBridge switched off, thus also the plugin and the memory observed, he has filled in no way as with the running plugin.
<img width="1260" alt="2022-07-24 at 10 30 Uhr (Reboot)" src="https://user-images.githubusercontent.com/109787025/180734722-5020aeb4-042d-4043-a7f6-ff9acd5349ed.png">
<img width="1293" alt="2022-07-24 at 16 30 Uhr" src="https://user-images.githubusercontent.com/109787025/180734736-91909a65-051a-4d1c-bb03-ba4170fce4d4.png">
<img width="1287" alt="2022-07-24 at 21 Uhr" src="https://user-images.githubusercontent.com/109787025/180734741-39cd97a7-fc8a-4fa4-b517-95c6a232b6a4.png">
<img width="1375" alt="2022-07-25 at 08 Uhr" src="https://user-images.githubusercontent.com/109787025/180734743-4afadeec-a275-4d20-b12a-64bbe1e1fd90.png">

But I will still send you screenshots in the next few days

**Comment by Vollerplasc** [comment]
Screenshots from yesterday until 11am toda
<img width="1320" alt="(05) 2022-07-25 at  11 15 Uhr neu" src="https://user-images.githubusercontent.com/109787025/180971499-66cf9bcf-e60f-46da-a1e9-ba7f01678e30.png">
<img width="1354" alt="(06) 2022-07-25 at 23 00 Uhr" src="https://user-images.githubusercontent.com/109787025/180971511-78970fb9-8d99-423e-ba66-642e023ac8c7.png">
<img width="1284" alt="(07) 2022-07-26 at 09 00 Uhr " src="https://user-images.githubusercontent.com/109787025/180971516-08fd5e6b-d802-4cd6-a4c5-3a9af6c99dcd.png">
<img width="1269" alt="(08) 2022-07-26 at 11 00 Uhr" src="https://user-images.githubusercontent.com/109787025/180971522-41a2e4c5-f070-400f-8300-1794b4a74853.png">
y

**Comment by ebaauw** [comment]
So memory usage of the child bridge with Homebridge SOMA is increasing slightly, but not dramatically.  And still lower than memory usage of the main Homebridge or `hb-service`.  You do see that the swap file is now being used slightly.  I take it, the system is still responsive?

**Comment by Vollerplasc** [comment]
Yes it is slowly increasing, the system is still responding. From the last observations, the free memory increases until only 0.03 GB are free, then I can no longer get on the Homebridge drauf, but unfortunately missed it to log in via the terminal, if I can still see something, I hope that it works this time

**Comment by Vollerplasc** [comment]
Yes, currently it is still responsive. Its running now for almost two days. after 5-7 days the memory fills more and more until it is maxed out and the website gets iresponsible.

But, and thats my observation here, only when the SOMA plugin is active. When i disable, uninstall or only restart it's child bridge the RAM frees up imediately, also the one from the homebridge process.
I am not a developer. I have no idea how. But my observation is pretty obvious, sadly.

A workaround is running this command:
sudo sh -c "echo 1 > /proc/sys/vm/drop_caches"
Afterwards the memory is also freed up without restarting the plugin.

I thought about creating a cron job to run this command every 24h, but this would not fix the error, only removing its impact for me.

**Comment by ebaauw** [comment]
This is not an issue with Homebridge SOMA, but with the overall memory usage of your system.  The memory usage of Homebridge SOMA seems OK.  It just happens to be the last program you added, causing the overall memory usage to hit the limit sooner.  Like the last person to enter the elevator triggering the overweight warning.  Not because the last person is too heavy, but because there's simply too many persons in the elevator.

> sudo sh -c "echo 1 > /proc/sys/vm/drop_caches"

This clears the file system cache (the blue and yellow parts in the _Mem_ bar in `htop`).  It doesn't impact the memory used by Homebridge SOMA, nor by any other program (the green part in the _Mem_ bar).  When _Mem_ fills, the system starts using _Swp_.  When _Swp_ fills, the system becomes unresponsive.  Basically, this command is the equivalent of kicking some other persons from the elevator.

In my experience, increasing the swap file from 100MB to 2GB prevents _Swp_ from filling, and consequently, the system from becoming unresponsive.  This is the equivalent of getting a bigger elevator, which, imho, beats kicking out people periodically.

**Comment by Vollerplasc** [comment]
I've been watching the htop progress for a few days now and noticed that first the RAM and then also the swap gradually filled up. 

Just when both were full, the Bluetooth connections to the individual SOMA drives began to break off. This freed up a little RAM each time, which then filled up again and again. From my observation, I would guess that your plugin is somehow filling up RAM along with the Bluetooth. 

I will uninstall your plugin now and monitor the homebridge for another week and send you comparison screenshots. This should show you that the RAM doesn't keep filling up without your plugin. Your elevator theory unfortunately does not fit here, because without the plugin a lot of memory is and remains constantly free.

<img width="1239" alt="(09) 2022-07-26 at 23 30 Uhr neu" src="https://user-images.githubusercontent.com/109787025/181814903-9a17d969-0d76-4356-ab2d-bcce0b687a74.png">
<img width="1233" alt="(10) 2022-07-27 um 06 30 Uhr" src="https://user-images.githubusercontent.com/109787025/181814913-504183d6-00d4-4105-938f-40812321bcc3.png">
<img width="1256" alt="(11)  2022-07-27 um 18 00 Uhr" src="https://user-images.githubusercontent.com/109787025/181814921-4a930c6a-8070-4a89-bf52-233f2e608963.png">
<img width="1337" alt="(12)2022-07-28 um 03 30 Uhr" src="https://user-images.githubusercontent.com/109787025/181814925-6b2a65ec-4295-4f9d-8b7b-5fbad1137e7b.png">
<img width="1273" alt="(13)2022-07-28 um 16 Uhr" src="https://user-images.githubusercontent.com/109787025/181814928-0cea19fd-5014-4fc2-a087-216dc32b1f48.png">
<img width="1414" alt="(14) 2022-07-28 17 45 Uhr" src="https://user-images.githubusercontent.com/109787025/181814931-25b7db6d-75b3-4909-9deb-7040b7faedd8.png">
<img width="1426" alt="(15) 2022-07-28 um 18 30 Uhr" src="https://user-images.githubusercontent.com/109787025/181814934-bde3a8e4-d943-4f69-8ddd-3b3c76e35443.png">
<img width="1266" alt="(16) 2022-07-28 um 20 00 Uhr" src="https://user-images.githubusercontent.com/109787025/181814936-373f77ac-529b-4d8d-a4b6-4bd5648bf9a4.png">
<img width="1261" alt="(17) 2022-07-28 um 21 00 Uhr" src="https://user-images.githubusercontent.com/109787025/181814938-7aa4bd36-adfb-4a1e-937e-25a09a966000.png">
<img width="1373" alt="(18) 2022-07-29 um 03 30 Uhr" src="https://user-images.githubusercontent.com/109787025/181814942-7544ca2b-4d76-4224-918c-c2c6df7cf100.png">
<img width="1336" alt="(19) 2022-07-29 um 04 30 Uhr" src="https://user-images.githubusercontent.com/109787025/181814946-d642e96b-a187-41d2-b291-efd8d703db3e.png">
<img width="1271" alt="(20) 2022-07-29 um 16 Uhr" src="https://user-images.githubusercontent.com/109787025/181814948-39fdfd4b-d6eb-46fc-93b5-ba3be11b7a08.png">
<img width="1241" alt="(21) 2022-07-29 um 18 30 Uhr" src="https://user-images.githubusercontent.com/109787025/181814949-a42621f6-cc6e-4379-93bf-44a8aa49c19e.png">
<img width="1197" alt="(22) 2022-07-29 um 19 30 Uhr" src="https://user-images.githubusercontent.com/109787025/181814951-7d916e36-c9cc-4e71-a00a-3d6441671399.png">

**Comment by ebaauw** [comment]
I’m sorry, I cannot help you.
