### ISSUE TITLE
Feature request: allows to specify which accessories to control

### ISSUE THREAD

**Issue by reididetnobal** [ebaauw/homebridge-soma#4]
hi Erik, 

I tried this plugin and it worked well for my purpose. There is a feature that I would like to be added / to add: one of my soma smart shade is a bit too far to connect properly to my main raspberry pi and I wanted to add a second one to control that specific smart shade. Since I would be running 2 instances of this plugin, I would like to specify which homebridge instance is controlling which smart shade (by specify a mac address somewhere in the config). 

I looked at the code and I can probably hack something, but before butchering your code, I resolved myself to ask I you planned to implement this feature.

best regards,

**Comment by ebaauw** [comment]
Sorry for replying so late; I mist have missed this issue earlier.

I really like keeping the config minimal; every config.json setting typically results in more issues.  Having said that, the implementation would be relatively simple: just filtering the advertisements against a whitelist.  I have that logic already in the `soma` command-line tool, where you specify the shade name or Mac address to probe.

Alternatively, Noble does report the RSSI for advertisements, I just never looked at it until now.  Maybe we could use that to filter out too weak a signal to connect?  I changed `soma discover` to report the RSSI in the latest beta.  Could you try and run that, to see what level the far shade reports vs the shades closer by?

I think Homebridge SOMA will only create an accessory once it has connected successfully.  Of course, it will continue to try as long as it receives advertisements.

**Comment by Djelibeybi** [comment]
I have the almost same problem and request. Here's my output:

```
soma discover: XX:XX:XX:XX:XX:XX: Office (Smart Shades), position: 100%, battery: 68%, rssi: -89
soma discover: YY:YY:YY:YY:YY:YY: Bedroom (Smart Shades), position: 100%, battery: 37%, rssi: -79
```

In my case, the Office Shades are close enough to be discovered and controlled _most_ of the time. But I do get a lot of unexpected disconnects.

**Comment by ebaauw** [comment]
I'm seeing unexpected disconnects myself as well.  I don't think they're necessarily related to signal strength.  I'm seeing RSSI values between -71 and -79 for my four Tilt 2 devices.  I'm running Homebridge Soma on a Raspberry Pi 4B in a heatsink case at ~4 meters distance with straight line of sight to each.  I oriented the Pi so that the Bluetooth antenna (above the uSD card) is facing the Tilts, but I think the heatsink case might still partially block the Bluetooth signal.  The Pi is wired to ethernet and its WifI is off.

Done some more testing with various hosts:

Tilt | Pi 4B | Pi Zero W | 2011<br>Mac mini<br>server | 2015<br>MacBook Pro | 2018<br>Mac mini 
--- | --- | --- | --- | --- | ---
Office | -73 | -77 | -92 | -68 | -67
Living Room 1 | -75 | -74 | -94 | -73 | --
Living Room 2 | -77 | -77 | -83 | -77 | --
Living Room 3 | -78 | -76 | __-95__ | -85 | --

The Pi 4B is my production machine running Homebridge SOMA, as mentioned in the previous paragraph.  The Pi Zero W and Mac mini server are in the wiring closet, I think ~9 meters distance from the Tilts, with an obstructed light of sight.  The MacBook Pro and Mac mini sit on my desk, at ~2 to ~5m distance, with no direct line of sight to the Living Room Tilts in the bay window.  The 2018 Mac mini is suffering badly from USB-3 interference, and only discovers the Office Tilt.  The Mac mini server discovers the Living Room 3 Tit, but fails to connect, or disconnects while discovering all services and characteristics.

Possibly unrelated, I'm also getting a notification timeout when first connecting to each Tilt after restarting Homebridge SOMA.  It almost seems deterministic, but I have no clue what would be causing it.

I think some unexpected disconnects come with the BLE territory; maybe I should implement some automatic retry on this, before giving up and waiting for the next polling cycle to retry.  Sometimes nRF Connect on my iPad fails to connect or loses connection to a Tilt as well, even at a direct line of sight distance of ~2m.

**Comment by ebaauw** [comment]
Could you folks try v1.0.1?  This version allows setting a minimum RSSI value for discovered devices to be exposed.  This version also exposes the RSSI value to HomeKit, and includes it in `connected` debug messages, to aid in finding the optimal value for each Homebridge SOMA installation.

Note that the setting only works for newly discovered devices.  Homebridge SOMA won't un-expose previously exposed devices with a low RSSI; you need to remove these from the Homebridge cache yourself (in the UI under _Manage Cached Accessories_ under _Homebridge Settings_).

**Comment by Djelibeybi** [comment]
I hadn't actually considered disabling the wifi on the Pi that runs my SOMA bridge and given that it uses the new Homebridge OS image, it's doing an endless cycle of wifi AP enable/scan/disable. Let me disable the wifi completely to see if that makes a difference.

Having said that, I still think being able to configure an allow/deny list of devices is useful. It's the thing that irritated me the most about the SOMA Connect. I could only run one, because it could see all my blind motors, even if I wanted to isolate certain devices away (for testing purposes, etc).

**Comment by ebaauw** [comment]
In v1.0.3.

> BTW, not sure if you code in Python or even use Home Assistant, but its SOMA integration could use a little bit of your magic

I don't use Home Assistant, nor any other Home automation system.  I use deCONZ rules (some 300 now) for automating my Zigbee devices and HomeKit automations and button actions for the non-Zigbee devices (and of course, on-device triggers for SOMA).  I not looking to add another component, although Home Assistant would probably be more stable than HomeKit automations.

> I think there's still an occasional RangeError for unknown service key or unknown characteristic key when not all services and/or characteristics are discovered on initial connect. Hard to reproduce and I would probably need to refactor the whole setup logic to address that.

Unfortunately, that's still the case, see #6.
